name: BluSkills
favicon: null
layout_spectrum: 0.07943
typography_spectrum: 0.88712
title: 'BluSkills Security & Security Chauffeur'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f21'
    - '#c0ced7'
    - '#99a5b1'
    - '#6a6d7e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
