typography_spectrum: 0.8606
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.11740012932568789
  lightness: 0.6970909971278161
  saturation: 0.43011553306132555
  rhythmicContrast: 0.16065946593880653
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09933
analytics:
  google: UA-53811712-1
  facebook: null
  twitter: null
logo: null
name: BluSkills
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e85f228-11a0-4a78-8ba3-b995126c8e58.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BluSkills Security & Security Chauffeur
description: Your 360° Security Solution
purpose: []
