typography_spectrum: 0.204229996772483
color:
  brandColors:
    - '#65686D'
    - '#FFFFFF'
    - '#A1A8B0'
    - '#D4D8DB'
    - '#121212'
  brandStrength: 0.31443383102305233
  lightness: 0.09580658725462854
  saturation: 0.2645539117511362
  rhythmicContrast: 0.7118746892083436
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.28170777624472976
analytics:
  google: UA-53811712-1
  facebook: null
  twitter: null
logo: null
name: BluSkills
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Privacy Policy
    id: c41a8880-e914-4abb-8e7d-e284b5ef45fb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e85f228-11a0-4a78-8ba3-b995126c8e58.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BluSkills Security & Security Chauffeur
description: Your 360° Security Solution
purpose: []
