typography_spectrum: 0.78846
color:
  brandColors:
    - '#ffffff'
    - '#1f1f21'
    - '#c0ced7'
    - '#99a5b1'
    - '#6a6d7e'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07943
analytics:
  google: UA-53811712-1
  facebook: null
  twitter: null
name: BluSkills
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Our Blog
    id: 563f1f6e-cdff-41c0-8583-77802ddd58f2
    type: content
  - name: Contact Us
    id: cc2a9239-b0fa-41ed-995e-20d1cc29677d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e85f228-11a0-4a78-8ba3-b995126c8e58.png
title: BluSkills Security & Security Chauffeur
description: Your 360° Security Solution
purpose: []
