typography_spectrum: 0.78846
color:
  brandColors:
    - '#ffffff'
    - '#1f1f21'
    - '#c0ced7'
    - '#99a5b1'
    - '#6a6d7e'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07943
analytics:
  google: UA-53811712-1
  facebook: null
  twitter: null
name: BluSkills
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e85f228-11a0-4a78-8ba3-b995126c8e58.png
title: BluSkills Security & Security Chauffeur
purpose: []
