name: BluSkills
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231b10'
    - '#fe2521'
    - '#ff9758'
    - '#806f68'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
