name: BluSkills
favicon: null
layout_spectrum: 0.7505169410724193
typography_spectrum: 0.74855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f70b7'
    - '#9d9d9c'
    - '#808080'
    - '#ffffff'
    - '#8e8e8e'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
