name: BluSkills
favicon: null
layout_spectrum: 0.24952
typography_spectrum: 0.74855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f21'
    - '#c0ced7'
    - '#99a5b1'
    - '#6a6d7e'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
