layout_spectrum: 0.672317435964942
typography_spectrum: 0.47238726215437055
color:
  saturation: 0.997248591389507
  brandStrength: 0.2987000341527164
  rhythmicContrast: 0.3484425628557801
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  lightness: 0.525019159540534
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-53811712-1
  facebook: null
name: BluSkills
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Our Operators
    id: 3f05abea-9541-488c-b9e5-2b80bf9fbe50
    type: content
  - name: Our Blog
    id: 563f1f6e-cdff-41c0-8583-77802ddd58f2
    type: content
  - name: Contact Us
    id: cc2a9239-b0fa-41ed-995e-20d1cc29677d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e85f228-11a0-4a78-8ba3-b995126c8e58.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BluSkills Security & Security Chauffeur
description: Your 360° Security Solution
purpose: []
